import { guid4, sortBy } from 'shared-base';
import { LocalStore } from './Soundboard.types';

// beautiful 9 colors palette with distinct colors
const colors = [
  '#e6194b',
  '#3cb44b',
  '#ffe119',
  '#4363d8',
  '#f58231',
  '#911eb4',
  '#42d4f4',
  '#f032e6',
  '#bfef45',
].sort();

export const localStore: LocalStore = {
  localState: {
    activityId: '1',
    start: 0,
    duration: 0,
    endOfDayTime: 22,
    minutesLeftToday: 0,
    sessionId: guid4(),
  },
  activities: {
    '3': {
      id: '3',
      name: 'Exercise',
      color: colors[0],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '5': {
      id: '5',
      name: 'Projects',
      color: colors[1],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '8': {
      id: '8',
      name: 'Hobbies',
      color: colors[2],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '6': {
      id: '6',
      name: 'Home',
      color: colors[3],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '4': {
      id: '4',
      name: 'Meditate',
      color: colors[4],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '0': {
      id: '0',
      name: 'Idle',
      color: colors[5],
      todayDesired: 8 + 'h',
      desiredDurationDay: 8 + 'h',
      desiredDurationWeek: 40 + 'h',
      desiredDurationMonth: 160 + 'h',
      desiredDurationYear: 1920 + 'h',
    },
    '7': {
      id: '7',
      name: 'Organize',
      color: colors[6],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '2': {
      id: '2',
      name: 'Read',
      color: colors[7],
      todayDesired: 1 + 'h',
      desiredDurationDay: 1 + 'h',
      desiredDurationWeek: 5 + 'h',
      desiredDurationMonth: 20 + 'h',
      desiredDurationYear: 240 + 'h',
    },
    '1': {
      id: '1',
      name: 'Work',
      color: colors[8],
      todayDesired: 8 + 'h',
      desiredDurationDay: 8 + 'h',
      desiredDurationWeek: 40 + 'h',
      desiredDurationMonth: 160 + 'h',
      desiredDurationYear: 1920 + 'h',
    },
  },
  sessions: {
    '0': {
      id: '0',
      activityId: '0',
      start: Date.now(),
      end: Date.now(),
      duration: 1000,
    },
  },
};
